# Create a new post
POST http://localhost:3000/api/blog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzg3ZDg0ZThjM2UxMDcwYzliYzg5YzgiLCJlbWFpbCI6InVzZXJAbG9jYWwubG9jYWwiLCJuYW1lIjoiTmFtZSIsImlhdCI6MTczNzE5NDA2NiwiZXhwIjoxNzM5Nzg2MDY2fQ.a3Klho6gnAMzGSsGJZkVfIUyZCAbUk1cOotJxiJJ7i4
Content-Type: application/json

{
  "type": "video",
  "tags": ["taG1", "tag2", "tttt2", "tttt2", "tttt1", "tttt1"],
  "title": "asdasdsaasdasdsaasdasdsaasd",
  "url": "http://localhost.ru/sadasd"
}

###
