# Get posts
GET http://localhost:3000/api/posts HTTP/1.1
###

# Get posts query
GET http://localhost:3000/api/posts?tag=aa HTTP/1.1
###

# Get post by ID
GET http://localhost:3000/api/posts/eab06dc6-ba52-4169-a369-f2f825d44ebb HTTP/1.1

###

# Get post by ID
GET http://localhost:3000/api/posts/9059dee5-7897-46d3-b8f6-e075a8b568c0 HTTP/1.1

###

# Create a new post
POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "video",
  "tags": ["taG1", "tag2", "tttt2", "tttt2", "tttt1", "tttt1"],
  "title": "asdasdsaasdasdsaasdasdsaasd",
  "url": "http://localhost.ru/sadasd",
  "text": "asdasdsaasdasdsaasdasdsaasdasdsaasdasdsaasdasdsaasdasdsaasdasdsaasdasdsaasdasdsaasdasdsaasdasdsaasdasdsa"
}

###

# Update post by ID
PATCH http://localhost:3000/api/posts/9059dee5-7897-46d3-b8f6-e075a8b568c0 HTTP/1.1
Content-Type: application/json

{
  "type": "video",
  "tags": ["taG111", "tag2", "tttt2", "tttt2", "tttt1", "tttt1"],
  "title": "asdasdsaasdasdsaasdasdsaasd",
  "url": "http://localhost.ru/sadasd"
}

###

PATCH http://localhost:3000/api/posts/9059dee5-7897-46d3-b8f6-e075a8b568c0 HTTP/1.1
Content-Type: application/json

{
  "type": "quote",
  "tags": ["taG111", "tag2", "tttt2", "tttt2", "tttt1", "tttt1"],
  "quoteText": "quote text quote text quote text",
  "quoteAuthor": "quote author"
}

###

# Delte post by ID
DELETE http://localhost:3000/api/posts/04fbbb3a-68f6-4238-9247-2cd6686b01ed HTTP/1.1

###
