# Create a new user
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@local.local",
  "name": "Keks",
  "name1111": "Keks1asdasdasdasdasdasdasdasdasddsadasd11",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/users/677e5f315c8166b2ea7f7015 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@local.local",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:3000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzdlNWYzMTVjODE2NmIyZWE3ZjcwMTUiLCJlbWFpbCI6InVzZXJAbG9jYWwubG9jYWwiLCJuYW1lIjoiS2VrcyIsInRva2VuSWQiOiJmYjU5OTBkZi02Yjc0LTQ3NDMtOGI0ZC01MjY2ZGFkYzM1MzQiLCJpYXQiOjE3MzY3NjMzNjcsImV4cCI6MTczOTM1NTM2N30.6EG-hru-ShbvYPDeWpr6FVMiUJVS9HnKeXAvyg-7wL8

###

# Check user token
POST http://localhost:3000/api/users/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzdlNWYzMTVjODE2NmIyZWE3ZjcwMTUiLCJlbWFpbCI6InVzZXJAbG9jYWwubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczNjc0Nzg2NiwiZXhwIjoxNzM2NzQ4MTY2fQ.1BHbfTjaWESWSoNauE-R79JgsBT9WesglhwN3LHtZtw

###
