# Create a new comment for postId
POST http://localhost:4100/api/post-comments/eab06dc6-ba52-4169-a369-f2f825d44ebb HTTP/1.1
Content-Type: application/json

{
  "message": "comment comment"
}

###

# Get comments by postId
GET http://localhost:4100/api/post-comments/eab06dc6-ba52-4169-a369-f2f825d44ebb HTTP/1.1

###

# Delete comment by postId
DELETE http://localhost:4100/api/post-comments/eab06dc6-ba52-4169-a369-f2f825d44ebb HTTP/1.1

###
