export enum ConfigAlias {
  NodeEnv = 'NODE_ENV',
  Host = 'host',
  HostEnv = 'HOST',
  Port = 'port',
  PortEnv = 'PORT',
  User = 'user',
  UserEnv = 'USER',
  Password = 'password',
  PasswordEnv = 'PASSWORD',
  Database = 'database',
  DatabaseEnv = 'DATABASE',
  AuthBase = 'authBase',
  AuthBaseEnv = 'AUTHBASE',
  UploadDirectoryPath = 'uploadDirectoryPath',
  UploadDirectoryEnv = 'UPLOAD_DIRECTORY_PATH',
  ServeRoot = 'serveRoot',
  ServeRootEnv = 'SERVE_ROOT',

  Application = 'application',
  AppPort = `${Application}.${Port}`,
  AppUploadDirectoryPath = `${Application}.${UploadDirectoryPath}`,
  AppServeRoot = `${Application}.${ServeRoot}`,

  MongoDbEnv = 'MONGODB',
  MongoDbHostEnv = `${MongoDbEnv}_${HostEnv}`,
  MongoDbPortEnv = `${MongoDbEnv}_${PortEnv}`,
  MongoDbUserEnv = `${MongoDbEnv}_${UserEnv}`,
  MongoDbPasswordEnv = `${MongoDbEnv}_${PasswordEnv}`,
  MongoDbDatabaseEnv = `${MongoDbEnv}_${DatabaseEnv}`,
  MongoDbAuthBaseEnv = `${MongoDbEnv}_${AuthBaseEnv}`,

  AppMongoDb = `${Application}.mongoDb`,
  AppMongoDbHost = `${AppMongoDb}.${Host}`,
  AppMongoDbPort = `${AppMongoDb}.${Port}`,
  AppMongoDbUser = `${AppMongoDb}.${User}`,
  AppMongoDbPassword = `${AppMongoDb}.${Password}`,
  AppMongoDbDatabase = `${AppMongoDb}.${Database}`,
  AppMongoDbAuthBase = `${AppMongoDb}.${AuthBase}`,

  PostgresEnv = 'POSTGRES',
  PostgresHostEnv = `${PostgresEnv}_${HostEnv}`,
  PostgresPortEnv = `${PostgresEnv}_${PortEnv}`,
  PostgresUserEnv = `${PostgresEnv}_${UserEnv}`,
  PostgresPasswordEnv = `${PostgresEnv}_${PasswordEnv}`,
  PostgresDatabaseEnv = `${PostgresEnv}_${DatabaseEnv}`,

  AppPostgres = `${Application}.postgres`,
  PostgresHost = `${AppPostgres}.${Host}`,
  PostgresPort = `${AppPostgres}.${Port}`,
  PostgresUser = `${AppPostgres}.${User}`,
  PostgresPassword = `${AppPostgres}.${Password}`,
  PostgresDatabase = `${AppPostgres}.${Database}`,

  JwtEnv = 'JWT',
  JwtAccessTokenSecretEnv = `${JwtEnv}_ACCESS_TOKEN_SECRET`,
  JwtAccessTokenExpiresInEnv = `${JwtEnv}_ACCESS_TOKEN_EXPIRES_IN`,
  JwtRefreshTokenSecretEnv = `${JwtEnv}_REFRESH_TOKEN_SECRET`,
  JwtRefreshTokenExpiresInEnv = `${JwtEnv}_REFRESH_TOKEN_EXPIRES_IN`,

  AppJwt = `${Application}.jwt`,
  AppJwtAccessTokenSecret = `${AppJwt}.accessTokenSecret`,
  AppJwtAccessTokenExpiresIn = `${AppJwt}.accessTokenExpiresIn`,
  AppJwtRefreshTokenSecret = `${AppJwt}.refreshTokenSecret`,
  AppJwtRefreshTokenExpiresIn = `${AppJwt}.refreshTokenExpiresIn`
}
